version: '3.8'

services:
  ros2_mapless_navigation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_mapless_navigation
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./models:/ros2_ws/models  # 学習済みモデルの永続化
      - ./results:/ros2_ws/results  # 評価結果の永続化
      - ./logs:/ros2_ws/logs  # ログの永続化
    network_mode: host  # ROS2通信のためにホストネットワークを使用
    privileged: true  # Gazeboのためのハードウェアアクセス
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash  # 起動時はbashシェルを開く